Improved config mgmt and fixed out of bounds panic
praetorian-inc/gokart pull request #5
Opened 2021-08-19 01:59 UTC by jessesomerville

Changed the way the config is loaded to use defined structs instead of nested maps of interface{}.  Now, the config is loaded into a struct during initialization and the values are referenced by the struct fields as appropriate.  This refrains from reading and parsing the config file twice (once when loading the default sources and again when loading any analyzers.

Additionally, this change adds a length check to fix the panic shown in https://github.com/praetorian-inc/gokart/issues/2

2021-08-19 02:01 UTC, jessesomerville commented
@isp1r0 @praetorian-harry I can break this into multiple PRs if that would be preferred.  I just decided to include the fix for #2 in this PR along with the configuration stuff because it was blocking me from testing.

2021-08-19 15:44 UTC, michaelweber requested changes
The code looks good + no issue with stacking multiple changes in one PR. It does look like if the older `analyzers.yml` file exists, it won't be loaded correctly and the scan will return zero results. This is from changing the format of `analyzers.yml` slightly, so we'll need some code to handle importing the "legacy" format (or just translating it when reading it) otherwise anyone that has installed gokart already will have their install break).

Repro steps are pretty much:

1. Download the `analyzers.yml` file at https://raw.githubusercontent.com/praetorian-inc/gokart/main/util/analyzers.yml and write it to your `.gokart` directory.
2. Run `gokart scan` against a directory that SHOULD return vulns.
3. Observe that no results are displayed.


For example, if I run against the [go-test-bench](https://github.com/Contrast-Security-OSS/go-test-bench) project with an existing config in place, my results are:

~~~
% ./gokart scan ../../go-test-bench 
Using config found at /Users/weber/.gokart/analyzers.yml

Revving engines VRMMM VRMMM
3...2...1...Go!

Race Complete! Analysis took 534.507134ms and 313 Go files were scanned (including imported packages)
GoKart found 0 potentially vulnerable functions
~~~

Are you cool with adding some backwards compatibility to this PR before we merge it?

2021-08-19 17:32 UTC, jessesomerville commented
Added a fix for that in `util/config.go`.  Let me know if that works for you!

2021-08-19 17:38 UTC, michaelweber approved these changes

2021-08-19 17:39 UTC, merged

2021-08-19 17:39 UTC, michaelweber commented
That fixed it, you rock @jessesomerville!

2021-08-21 22:08 UTC, Hacman1 commented
Kinda new to this, it looks wired to me. 
Can you help me with coding.